name: Push to GitHub Pages

on:
    push:
    workflow_dispatch:

jobs:
    check:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2
              with:
               path: /home/runner/work/jumblejot/jumblejot/a
            - uses: actions/checkout@v2
              with:
                repository: jumblejot/jumblejot.github.io
                path: /home/runner/work/jumblejot/jumblejot/b

            - name: Push
              run: |
                git config --global user.name "github-actions"
                git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"
                cd /home/runner/work/jumblejot/jumblejot
                ls
                rsync -r ./a/ ./b --exclude=.git
                cd b
                git add .
                git commit -m "Pull in changes"
                git push
