name: Push to GitHub Pages

on:
    push:
    workflow_dispatch:

permissions:
  contents: write

jobs:
    check:
        runs-on: ubuntu-latest
        steps:
            - name: Push
              run: |
                git clone https://${{ github.token }}@github.com/jumblejot/jumblejot a
                git clone https://${{ github.token }}@github.com/jumblejot/jumblejot.github.io b
                ls
                rsync -r ./a/ ./b --exclude=.git
                cd b
                git add .
                git commit -m "Pull in changes"
                git push https://${{ github.token }}@github.com/jumblejot/jumblejot.github.io
