name: Push to GitHub Pages

on:
    push:
    workflow_dispatch:

jobs:
    check:
        runs-on: ubuntu-latest
        steps:
            - name: Push
              run: |
                git config --global user.name github-actions
                git config --global user.email github-actions@github.com
                git clone https://${{ secrets.GITHUB_TOKEN }}@github.com/jumblejot/jumblejot
                git clone https://${{ secrets.GITHUB_TOKEN }}@github.com/jumblejot/jumblejot.github.io
                ls
                rsync -r ./jumblejot/ ./jumblejot.github.io --exclude=.git
                cd jumblejot.github.io
                git add .
                git commit -m "Pull in changes"
                git push
