name: Push to GitHub Pages

on:
    push:
    workflow_dispatch:

jobs:
    check:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2
              with:
               path: /home/runner/work/jumblejot
            - uses: actions/checkout@v2
              with:
                repository: jumblejot/jumblejot.github.io
                path: /home/runner/work/jumblejot.github.io
            - uses: fregante/setup-git-user@v1

            - name: Push
              run: |
                cd /home/runner/work
                ls
                rsync -r ./jumblejot/ ./jumblejot.github.io --exclude=.git
                cd jumblejot.github.io
                git add .
                git commit -m "Pull in changes"
                git push
